var DPMW;
(function (DPMW) {
    var Model;
    (function (Model) {
        var Content;
        (function (Content) {
            Content.PARSE_NAME_ENTRY_LIST = 'entry_list';
            Content.LIMIT = 100;
            Content.UPDATE_VALUE_NAME_PARENT_FOLDER_ID = 'parent_folder_id';
            Content.UPDATE_VALUE_NAME_FILE_NAME = 'file_name';
            Content.UPDATE_VALUE_NAME_FOLDER_NAME = 'folder_name';
            Content.ATTR_NAME_ENTRY_ID = 'entry_id';
            Content.ATTR_NAME_ENTRY_NAME = 'entry_name';
            Content.ATTR_NAME_ENTRY_PATH = 'entry_path';
            Content.ATTR_NAME_ENTRY_TYPE = 'entry_type';
            Content.ATTR_NAME_CREATED_DATE = 'created_date';
            Content.ATTR_NAME_MODIFIED_DATE = 'modified_date';
            Content.ATTR_NAME_MIME_TYPE = 'mime_type';
            Content.ATTR_NAME_FILE_SIZE = 'file_size';
            Content.ATTR_NAME_DOCUMENT_TYPE = 'document_type';
            Content.ATTR_NAME_AUTHOR = 'author';
            Content.ATTR_NAME_TITLE = 'title';
            Content.ATTR_NAME_TOTAL_PAGE = 'total_page';
            Content.ATTR_NAME_READING_DATE = 'reading_date';
            Content.ATTR_NAME_PARENT_FOLDER_ID = 'parent_folder_id';
            Content.ATTR_NAME_IS_NEW = 'is_new';
            Content.ATTR_NAME_DOCUMENT_SOURCE = 'document_source';
            Content.ATTR_NAME_FILE_REVISION = 'file_revision';
            Content.VALUE_ENTRY_ID_ROOT = 'root';
            Content.VALUE_ENTRY_PATHD_ROOT = 'document/';
            Content.VALUE_ENTRY_TYPE_FILE = 'document';
            Content.VALUE_ENTRY_TYPE_FOLDER = 'folder';
            Content.VALUE_DOCUMENT_TYPE_NOT_NOTE = 'normal';
            Content.VALUE_DOCUMENT_TYPE_NOTE = 'note';
            Content.ORDER_TYPE_ENTRY_NAME_ASC = 'entry_name_asc';
            Content.ORDER_TYPE_ENTRY_NAME_DESC = 'entry_name_desc';
            Content.ORDER_TYPE_CREATED_DATE_ASC = 'created_date_asc';
            Content.ORDER_TYPE_CREATED_DATE_DESC = 'created_date_desc';
            Content.ORDER_TYPE_MODIFIED_DATE_ASC = 'modified_date_asc';
            Content.ORDER_TYPE_MODIFIED_DATE_DESC = 'modified_date_desc';
            Content.ORDER_TYPE_READING_DATE_ASC = 'reading_date_asc';
            Content.ORDER_TYPE_READING_DATE_DESC = 'reading_date_desc';
            Content.ORDER_TYPE_TITLE_ASC = 'title_asc';
            Content.ORDER_TYPE_TITLE_DESC = 'title_desc';
            Content.ORDER_TYPE_AUTHOR_ASC = 'author_asc';
            Content.ORDER_TYPE_AUTHOR_DESC = 'author_desc';
            Content.ORDER_TYPE_FILE_SIZE_ASC = 'file_size_asc';
            Content.ORDER_TYPE_FILE_SIZE_DESC = 'file_size_desc';
            Content.ENTRY_TYPE_ALL = 'all';
            Content.ENTRY_TYPE_DOCUMENTS = 'documents';
            Content.ENTRY_TYPE_NOTES = 'notes';
            Content.SEARCH_TARGET_DOCUMENT_META = 'document_meta';
            Content.SEARCH_TARGET_DOCUMENT_BODY = 'document_body';
            Content.SEARCH_TARGETE_ANNOTATION_PATTERN = 'annotation_pattern';
            Content.ANNOTATION_TYPE_ALL = 'all';
            Content.ANNOTATION_TYPE_HIGHLIGHTS = 'highlights';
            Content.ANNOTATION_TYPE_HANDWRITINGS = 'handwritings';
            Content.ANNOTATION_KEYWORDE_STAR = 'star';
            Content.ANNOTATION_KEYWORDE_ASTERISK = 'asterisk';
            Content.PARSE_NAME_COUNT = 'count';
            Content.ATTR_NAME_TOTAL_COUNT = 'total_count';
        })(Content = Model.Content || (Model.Content = {}));
    })(Model = DPMW.Model || (DPMW.Model = {}));
})(DPMW || (DPMW = {}));
//# sourceMappingURL=ContentDefs.js.map